In [1]:
import scipy.io
import numpy as np
import pandas as pd

In [62]:
f = scipy.io.loadmat('ex4data1.mat')
data=f['X']
out=f['y']
x,y=data.shape
out.shape

(5000, 1)

In [63]:
one=np.ones((x,1))
one
data1=np.hstack((data,one))
x1,y1=data1.shape
data1[:5,:]

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [64]:
W1=np.random.randn(26,y1)
W1.shape
W1[:5,:]

array([[-1.98739640e+00,  4.56192980e-01,  2.59748793e-01, ...,
        -6.04059369e-01,  1.67579887e+00,  7.54011035e-01],
       [ 1.46619365e+00,  1.18090974e+00,  9.27387066e-01, ...,
         2.35955387e+00, -1.13786157e+00, -1.83735250e-01],
       [ 4.02220530e-01,  1.78571557e-03, -1.25806357e+00, ...,
         3.00011569e-01,  3.07236156e-01,  5.11792995e-01],
       [ 7.35803911e-01, -4.94367488e-01, -1.40333197e-01, ...,
        -1.60712257e+00,  1.05483788e+00, -6.94338290e-02],
       [ 5.00937318e-02,  7.44201532e-01,  5.55524897e-01, ...,
         6.56784029e-01,  5.22668991e-01,  2.19113114e+00]])

In [65]:
data2=np.dot(W1,data1.T)
data2.shape
data2[:5,:]

array([[  2.46282132,   0.80802744,  -0.78626504, ...,  -4.27817585,
          4.26718965,   4.8180396 ],
       [ -7.58334347,  -9.14836091,  -2.42394518, ...,  -2.72219386,
         -5.79904861, -11.08804856],
       [ -2.82320647,  -7.04597672,   2.25009035, ...,   0.75415028,
         -7.65330531,  10.80135027],
       [  1.05511899,  -4.13387086,  -4.8709234 , ...,  -2.11624476,
         -8.17123301,  -2.8499579 ],
       [  4.63051809,   3.41684146,  11.17208158, ...,   4.73050835,
          1.46601424,   7.63822039]])

In [70]:
def sigmoid(data):
    return 1/(1+np.exp(-1*data))

In [71]:
def maximizer(data):
    return np.argmax(data,axis=1)

In [76]:
act_data2=sigmoid(data2)
x3,y3=act_data2.shape
act_data2[:5,:]

array([[9.21494008e-01, 6.91689005e-01, 3.12971199e-01, ...,
        1.36782472e-02, 9.86172742e-01, 9.91982188e-01],
       [5.08598224e-04, 1.06382731e-04, 8.13648873e-02, ...,
        6.16763801e-02, 3.02128071e-03, 1.52937876e-05],
       [5.60829490e-02, 8.70147995e-04, 9.04658328e-01, ...,
        6.80082351e-01, 4.74248234e-04, 9.99979628e-01],
       [7.41756674e-01, 1.57681275e-02, 7.60795822e-03, ...,
        1.07527914e-01, 2.82589388e-04, 5.46834937e-02],
       [9.90344432e-01, 9.68226747e-01, 9.99985939e-01, ...,
        9.91255162e-01, 8.12450815e-01, 9.99518547e-01]])

In [73]:
# one2=np.ones((1,x1))
# act_data2=np.vstack((act_data2,one2))

In [77]:
W2=np.random.randn(10,x3)
W2.shape

(10, 26)

In [78]:
data3=np.dot(W2,act_data2)
act_data3=sigmoid(data3).T
act_data3.shape
act_data3[:5,:]

array([[2.47191456e-03, 2.24537394e-02, 6.48226116e-05, 9.96267850e-01,
        7.30485358e-01, 9.24760483e-01, 1.51474401e-02, 7.94736086e-01,
        1.34812047e-03, 7.41874967e-01],
       [3.22234099e-03, 8.65145461e-02, 3.36391562e-04, 9.94588419e-01,
        5.64211855e-01, 9.45707044e-01, 7.07406306e-03, 6.78422772e-01,
        3.43348388e-03, 7.26557518e-01],
       [1.02344089e-02, 2.50852473e-02, 9.43990496e-05, 9.84503965e-01,
        5.64803566e-01, 1.72717454e-01, 2.05557409e-02, 7.47920659e-01,
        4.33625325e-02, 8.96503029e-01],
       [1.50841031e-02, 2.76720954e-01, 1.52399976e-04, 9.90397035e-01,
        6.59061812e-01, 8.64180891e-01, 1.18851330e-01, 1.36567926e-01,
        4.65105015e-03, 9.87250671e-01],
       [1.28178488e-03, 1.42382787e-01, 2.00493906e-04, 7.72816030e-01,
        8.68178105e-01, 9.43899196e-01, 2.50449200e-02, 7.20489123e-01,
        4.22160987e-03, 5.02286926e-01]])

In [79]:
prediction_final=maximizer(act_data3)
prediction_final.shape

(5000,)

In [80]:
data_X=np.zeros((x1,10))
print(data_X.shape)
for i,j in zip(out,range(0,x1)):
    data_X[j,i%10]=1
data_X

(5000, 10)


array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [81]:
alpha=0.01
loss=1/x1*np.sum(np.sum((act_data3-data_X)**2,axis=1),axis=0)
loss

2.66864019462234

In [82]:
dz2=act_data3-data_X
print(dz.shape)
for i in range(0,10):
    if i==0:
         dw=np.sum(dz[:,i].T*act_data2,axis=1)
    else:
        x=np.sum(dz[:,i].T*act_data2,axis=1)
        dw=np.vstack((dw,x))
W2=W2-alpha*1/x1*dw
W2

(5000, 10)


array([[-0.44278521, -0.15105367, -0.55829702,  0.89505222, -0.23793795,
        -0.72089398, -2.21762184,  1.19830766, -1.01422514, -1.53000427,
        -1.28790379, -0.39971715, -0.08593172,  0.51066587,  1.14744708,
        -0.26911114, -0.68593228,  1.18188737,  0.15938653,  0.27510202,
         0.22854209, -1.53679462, -1.21859583,  1.19834811,  1.19581371,
        -0.42712693],
       [-1.99226698, -0.52599972, -0.32558971,  0.50443977,  1.27997612,
         0.04364602, -0.9519296 ,  2.62808714, -0.3276311 ,  0.19541095,
        -1.27501109,  0.15915429, -0.6629652 , -1.20013584,  0.46033871,
        -0.53690037, -1.47092239, -2.10954457,  1.14078427, -0.2715429 ,
         0.4084226 ,  0.00982008,  2.08974701, -1.58682144, -1.7911168 ,
         0.03142507],
       [-1.77964785, -0.30088737, -1.42235   , -1.22854949, -0.07345529,
        -1.58347712, -1.85222348, -0.95480871,  0.77913435, -0.58402589,
        -0.44052967, -0.68469541, -1.59078398, -0.38024983, -0.29962946,
       

In [84]:
dz1=np.dot(W2.T,dz2.T)*((act_data2*(1-act_data2)))
dw1=np.dot((np.dot(W2.T,dz2.T)*(act_data2*(1-act_data2))),data1)
W1=W1-alpha*1/x1*dw1
W1

array([[-1.98739640e+00,  4.56192980e-01,  2.59748791e-01, ...,
        -6.04059369e-01,  1.67579887e+00,  7.51804614e-01],
       [ 1.46619365e+00,  1.18090974e+00,  9.27387065e-01, ...,
         2.35955387e+00, -1.13786157e+00, -1.85591832e-01],
       [ 4.02220530e-01,  1.78571557e-03, -1.25806357e+00, ...,
         3.00011569e-01,  3.07236156e-01,  5.14229076e-01],
       ...,
       [-1.59266844e+00,  1.01875032e+00,  3.69154556e-01, ...,
         6.71852752e-01, -7.89608025e-01,  4.16224317e-03],
       [-2.70592219e-02, -1.52412540e+00, -5.72267748e-01, ...,
        -1.57465375e-01,  3.90661497e-02,  6.81707408e-01],
       [-8.21713650e-01,  5.30134044e-01,  5.27103412e-01, ...,
        -2.34913517e-01, -2.91302319e+00, -1.66419818e+00]])