In [1]:
import numpy as np
import pandas as pd
import collections

In [2]:
data=pd.read_csv('iris.data',header=None)
x,y=data.shape
r,c=x,y

In [3]:
data.head()

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [4]:
lis=data.iloc[:,4].unique()
dict={}
count=0
for i in lis:
    if i not in dict.keys():
        dict[i]=count
        count+=1
dict

{'Iris-setosa': 0, 'Iris-versicolor': 1, 'Iris-virginica': 2}

In [5]:
for i in range(0,x):
    data.iloc[i,4]=dict[data.iloc[i,4]]
data.tail()

0    1    2    3  4
145  6.7  3.0  5.2  2.3  2
146  6.3  2.5  5.0  1.9  2
147  6.5  3.0  5.2  2.0  2
148  6.2  3.4  5.4  2.3  2
149  5.9  3.0  5.1  1.8  2

In [6]:
cl=np.random.randint(5,30)
print(cl)
mem_matrix=np.random.random_sample((x,cl))

6


In [7]:
mem_matrix
mem_matrix=mem_matrix/np.sum(mem_matrix,axis=1).reshape(-1,1)
mem_matrix.shape

(150, 6)

In [8]:
m=np.random.rand(1)*np.random.randint(1,10)
m

array([3.70665575])

In [9]:
data1=data.to_numpy()
data1[:5,:]

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ]])

In [10]:
cent=[]
for i in range(0,cl):
    cent.append(np.sum(data1*((mem_matrix[:,i])**m).reshape(-1,1),axis=0)/np.sum((mem_matrix[:,i])**m))
cent

[array([5.64134988, 3.00798632, 3.44209169, 1.05024075, 0.8480207 ]),
 array([5.81645645, 3.04997992, 3.6433865 , 1.12951434, 0.94531296]),
 array([5.7585566 , 3.09157885, 3.5510539 , 1.13864624, 0.92431514]),
 array([5.95333006, 3.04796361, 4.06718774, 1.35571443, 1.12649809]),
 array([5.89285283, 3.06286618, 3.8576188 , 1.23065145, 1.00161217]),
 array([6.06126385, 3.05721267, 4.02961119, 1.29943996, 1.13033717])]

In [11]:
obj=0
for i in range(0,cl):
    obj+=np.sum(((mem_matrix[:,i])**m)*(np.sum((data1-cent[i])**2,axis=1)),axis=0)
obj

17.975826590824326

In [12]:
l=np.zeros((x,1))
for i in cent:
    l1=np.sqrt(np.sum((data1-i)**2,axis=1))
    l=np.hstack((l,l1.reshape(-1,1)))
l=l[:,1:]
l.shape
l[:5,:]

array([[2.47937977, 2.73974897, 2.63874075, 3.26359822, 2.98748408,
        3.24366677],
       [2.48230746, 2.76274988, 2.66607469, 3.29095259, 3.01580311,
        3.27919081],
       [2.63697063, 2.91857068, 2.81690542, 3.44324747, 3.16995061,
        3.43666045],
       [2.51130338, 2.79892613, 2.69899271, 3.32104453, 3.04904626,
        3.32001293],
       [2.52467756, 2.78559145, 2.68260103, 3.30637969, 3.03167585,
        3.28970886]])

In [13]:
new_mem_matrix=((1/l)**(1/(m-1)))/np.sum(((1/l)**(1/(m-1))),axis=0)
new_mem_matrix.shape
l=np.argmin(new_mem_matrix,axis=1)
l

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 0, 0, 0, 5, 0, 0, 0, 5, 0, 5, 5, 0, 3, 0, 5, 0,
       0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 5, 5, 0, 0, 0, 0, 0, 0,
       0, 5, 0, 0, 0, 5, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [14]:
for j in range(0,1000):
    cent=[]
    mem_matrix=new_mem_matrix
    for i in range(0,cl):
        cent.append(np.sum(data1*((mem_matrix[:,i])**m).reshape(-1,1),axis=0)/np.sum((mem_matrix[:,i])**m))
    cent
    l=np.zeros((x,1))
    for i in cent:
        l1=np.sqrt(np.sum((data1-i)**2,axis=1))
        l=np.hstack((l,l1.reshape(-1,1)))
    l=l[:,1:]
    new_mem_matrix=((1/l)**(1/(m-1)))/np.sum(((1/l)**(1/(m-1))),axis=0)
    obj=0
    for i in range(0,cl):
        obj+=np.sum(((new_mem_matrix[:,i])**m)*(np.sum((data1-cent[i])**2,axis=1)),axis=0)
    obj
    print(j," Objective Function:",obj)
l=np.argmin(new_mem_matrix,axis=1)
l

0  Objective Function: 2.0120186981386514e-05
1  Objective Function: 1.8970765845483465e-05
2  Objective Function: 1.8788517691762665e-05
3  Objective Function: 1.877980324795134e-05
4  Objective Function: 1.8792350625766467e-05
5  Objective Function: 1.8802973411819195e-05
6  Objective Function: 1.8809851720533324e-05
7  Objective Function: 1.881410249513489e-05
8  Objective Function: 1.881674141141943e-05
9  Objective Function: 1.8818411222065326e-05
10  Objective Function: 1.8819491924640278e-05
11  Objective Function: 1.8820207019352394e-05
12  Objective Function: 1.8820689825668927e-05
13  Objective Function: 1.8821021550646543e-05
14  Objective Function: 1.8821252833275375e-05
15  Objective Function: 1.8821416018215802e-05
16  Objective Function: 1.882153225028286e-05
17  Objective Function: 1.88216156520493e-05
18  Objective Function: 1.8821675836671784e-05
19  Objective Function: 1.882171945460582e-05
20  Objective Function: 1.882175116868806e-05
21  Objective Function: 1.88217

213  Objective Function: 1.8821837331368404e-05
214  Objective Function: 1.8821837331368404e-05
215  Objective Function: 1.8821837331368404e-05
216  Objective Function: 1.8821837331368404e-05
217  Objective Function: 1.8821837331368404e-05
218  Objective Function: 1.8821837331368404e-05
219  Objective Function: 1.8821837331368404e-05
220  Objective Function: 1.8821837331368404e-05
221  Objective Function: 1.8821837331368404e-05
222  Objective Function: 1.8821837331368404e-05
223  Objective Function: 1.8821837331368404e-05
224  Objective Function: 1.8821837331368404e-05
225  Objective Function: 1.8821837331368404e-05
226  Objective Function: 1.8821837331368404e-05
227  Objective Function: 1.8821837331368404e-05
228  Objective Function: 1.8821837331368404e-05
229  Objective Function: 1.8821837331368404e-05
230  Objective Function: 1.8821837331368404e-05
231  Objective Function: 1.8821837331368404e-05
232  Objective Function: 1.8821837331368404e-05
233  Objective Function: 1.8821837331368

402  Objective Function: 1.8821837331368404e-05
403  Objective Function: 1.8821837331368404e-05
404  Objective Function: 1.8821837331368404e-05
405  Objective Function: 1.8821837331368404e-05
406  Objective Function: 1.8821837331368404e-05
407  Objective Function: 1.8821837331368404e-05
408  Objective Function: 1.8821837331368404e-05
409  Objective Function: 1.8821837331368404e-05
410  Objective Function: 1.8821837331368404e-05
411  Objective Function: 1.8821837331368404e-05
412  Objective Function: 1.8821837331368404e-05
413  Objective Function: 1.8821837331368404e-05
414  Objective Function: 1.8821837331368404e-05
415  Objective Function: 1.8821837331368404e-05
416  Objective Function: 1.8821837331368404e-05
417  Objective Function: 1.8821837331368404e-05
418  Objective Function: 1.8821837331368404e-05
419  Objective Function: 1.8821837331368404e-05
420  Objective Function: 1.8821837331368404e-05
421  Objective Function: 1.8821837331368404e-05
422  Objective Function: 1.8821837331368

593  Objective Function: 1.8821837331368404e-05
594  Objective Function: 1.8821837331368404e-05
595  Objective Function: 1.8821837331368404e-05
596  Objective Function: 1.8821837331368404e-05
597  Objective Function: 1.8821837331368404e-05
598  Objective Function: 1.8821837331368404e-05
599  Objective Function: 1.8821837331368404e-05
600  Objective Function: 1.8821837331368404e-05
601  Objective Function: 1.8821837331368404e-05
602  Objective Function: 1.8821837331368404e-05
603  Objective Function: 1.8821837331368404e-05
604  Objective Function: 1.8821837331368404e-05
605  Objective Function: 1.8821837331368404e-05
606  Objective Function: 1.8821837331368404e-05
607  Objective Function: 1.8821837331368404e-05
608  Objective Function: 1.8821837331368404e-05
609  Objective Function: 1.8821837331368404e-05
610  Objective Function: 1.8821837331368404e-05
611  Objective Function: 1.8821837331368404e-05
612  Objective Function: 1.8821837331368404e-05
613  Objective Function: 1.8821837331368

787  Objective Function: 1.8821837331368404e-05
788  Objective Function: 1.8821837331368404e-05
789  Objective Function: 1.8821837331368404e-05
790  Objective Function: 1.8821837331368404e-05
791  Objective Function: 1.8821837331368404e-05
792  Objective Function: 1.8821837331368404e-05
793  Objective Function: 1.8821837331368404e-05
794  Objective Function: 1.8821837331368404e-05
795  Objective Function: 1.8821837331368404e-05
796  Objective Function: 1.8821837331368404e-05
797  Objective Function: 1.8821837331368404e-05
798  Objective Function: 1.8821837331368404e-05
799  Objective Function: 1.8821837331368404e-05
800  Objective Function: 1.8821837331368404e-05
801  Objective Function: 1.8821837331368404e-05
802  Objective Function: 1.8821837331368404e-05
803  Objective Function: 1.8821837331368404e-05
804  Objective Function: 1.8821837331368404e-05
805  Objective Function: 1.8821837331368404e-05
806  Objective Function: 1.8821837331368404e-05
807  Objective Function: 1.8821837331368

975  Objective Function: 1.8821837331368404e-05
976  Objective Function: 1.8821837331368404e-05
977  Objective Function: 1.8821837331368404e-05
978  Objective Function: 1.8821837331368404e-05
979  Objective Function: 1.8821837331368404e-05
980  Objective Function: 1.8821837331368404e-05
981  Objective Function: 1.8821837331368404e-05
982  Objective Function: 1.8821837331368404e-05
983  Objective Function: 1.8821837331368404e-05
984  Objective Function: 1.8821837331368404e-05
985  Objective Function: 1.8821837331368404e-05
986  Objective Function: 1.8821837331368404e-05
987  Objective Function: 1.8821837331368404e-05
988  Objective Function: 1.8821837331368404e-05
989  Objective Function: 1.8821837331368404e-05
990  Objective Function: 1.8821837331368404e-05
991  Objective Function: 1.8821837331368404e-05
992  Objective Function: 1.8821837331368404e-05
993  Objective Function: 1.8821837331368404e-05
994  Objective Function: 1.8821837331368404e-05
995  Objective Function: 1.8821837331368

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [15]:
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import matplotlib
from matplotlib import cm
# Points
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(data1[:,0], data1[:,3], data1[:,1] , c=l,cmap='rainbow',marker=',')
ax.set_xlabel('1st Feature')
ax.set_ylabel('2nd Feature')
ax.set_zlabel('3rd Feature')

Text(0.5, 0, '3rd Feature')

In [16]:
comp=np.hstack((l.reshape(-1,1),data1[:,4].reshape(-1,1)))
gr=[0,1,2]
acc=[]
for i in range(0,cl):
    x=comp[comp[:,0]==i]
    t=[]
    for j in gr:
        t.append(len(x[x[:,1]==j]))
    acc.append(t)
print(acc)
count=0
for i in acc:
    i.sort(reverse=True)
    count=count+i[0]
print('Accuracy:',(count/r)*100)
l

[[50, 50, 50], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]
Accuracy: 33.33333333333333


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)